name: hivedump
description: A sample command-line utility to dump hive database box contents.
version: 1.0.0
repository: https://github.com/alexnj/hivedump

environment:
  sdk: '>=2.19.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

dependencies:
  path: ^1.8.0
  hive: ^2.2.3
  args: ^2.4.0

